function onCreate()
    makeLuaSprite('vignette', 'doki/vignette', 0, 0)

    makeLuaSprite('sparklebg', 'doki/clubroom/YuriSparkleBG', 0, 0)
    setObjectCamera('sparklebg', 'hud')

    makeLuaSprite('sparklefg', 'doki/clubroom/YuriSparkleFG', 0, 0)
    scaleObject('sparklefg', 1.2, 1.2)
    updateHitbox('sparklefg')
    setObjectCamera('sparklefg', 'hud')

    makeAnimatedLuaSprite('doodles', 'doki/clubroom/BakaBGDoodles', 0, -20)
    setObjectCamera('doodles', 'hud')
    addAnimationByPrefix('doodles', 'normal', 'Normal Overlay', 24, true)
    addAnimationByPrefix('doodles', 'party rock is', 'Rock Overlay', 24, true)
    objectPlayAnimation('doodles', 'normal', true)
    setProperty('doodles.alpha', 0)
    scaleLuaSprite('doodles', 1.9, 1.8)
    updateHitbox('doodles')

    makeAnimatedLuaSprite('static', 'doki/clubroom/staticshock', 0, 0)
    setObjectCamera('static', 'other')
    addAnimationByPrefix('static', 'idle', 'hueh', 24, true)
    objectPlayAnimation('static', 'idle', true)

    makeLuaSprite('closet', 'doki/clubroom/DDLCfarbg', -700, -520)
    scaleLuaSprite('closet', 1.6, 1.6)
    updateHitbox('closet')
    setScrollFactor('closet', 0.9, 0.9)
    addLuaSprite('closet', false)

    makeLuaSprite('bg', 'doki/clubroom/DDLCbg', -700, -520)
    scaleLuaSprite('bg', 1.6, 1.6)
    updateHitbox('bg')
    setScrollFactor('bg', 1, 0.9)
    addLuaSprite('bg', false)

    makeLuaSprite('fg', 'doki/clubroom/DesksFront', -700, -520)
    scaleLuaSprite('fg', 1.6, 1.6)
    updateHitbox('fg')
    setScrollFactor('fg', 1.3, 0.9)
    addLuaSprite('fg', true)

    makeAnimatedLuaSprite('monika', 'doki/bgdoki/monika', 0, 0)
    addAnimationByPrefix('monika', 'idle', 'Moni BG', 24, false)
    setScrollFactor('monika', 1, 0.9)
    scaleLuaSprite('monika', 0.7, 0.7)
    updateHitbox('monika')

    makeAnimatedLuaSprite('sayori', 'doki/bgdoki/sayori', 0, 0)
    setScrollFactor('sayori', 1, 0.9)
    scaleLuaSprite('sayori', 0.7, 0.7)
    updateHitbox('sayori')
    addAnimationByPrefix('sayori', 'idle', 'Sayori BG', 24, false)

    makeAnimatedLuaSprite('natsuki', 'doki/bgdoki/natsuki', 0, 0)
    addAnimationByPrefix('natsuki', 'idle', 'Natsu BG', 24, false)
    setScrollFactor('natsuki', 1, 0.9)
    scaleLuaSprite('natsuki', 0.7, 0.7)
    updateHitbox('natsuki')

    makeAnimatedLuaSprite('protag', 'doki/bgdoki/protag', 0, 0)
    addAnimationByPrefix('protag', 'idle', 'Protag-kun BG', 24, false)
    setScrollFactor('protag', 1, 0.9)
    scaleLuaSprite('protag', 0.7, 0.7)
    updateHitbox('protag')

    makeAnimatedLuaSprite('yuri', 'doki/bgdoki/yuri', 0, 0)
    setScrollFactor('yuri', 1, 0.9)
    scaleLuaSprite('yuri', 0.7, 0.7)
    updateHitbox('yuri')
    addAnimationByPrefix('yuri', 'idle', 'Yuri BG', 24, false)
end