function onCreate()
    makeLuaSprite('bg2', 'miku/expo/nightsky', -280, -100)
    scaleObject('bg2', 1.1, 1.1)
    updateHitbox('bg2')
    setScrollFactor('bg2', 0.6, 0.6)
    addLuaSprite('bg2', false)

    makeLuaSprite('bg1', 'miku/expo/backlight', -285, -100)
    scaleObject('bg1', 1.1, 1.1)
    updateHitbox('bg1')
    setScrollFactor('bg1', 0.7, 0.7)
    addLuaSprite('bg1', false)

    makeLuaSprite('bg4', 'miku/expo/concerttop', -285, -100)
    scaleObject('bg4', 1.1, 1.1)
    updateHitbox('bg4')
    setScrollFactor('bg4', 0.75, 0.75)
    addLuaSprite('bg4', false)

    makeLuaSprite('bg3', 'miku/expo/stadiumback', -420, -100)
    scaleObject('bg3', 1.1, 1.1)
    updateHitbox('bg3')
    setScrollFactor('bg3', 0.8, 0.8)
    addLuaSprite('bg3', false)

    makeLuaSprite('bg5', 'miku/expo/speakers', -285, -100)
    scaleObject('bg5', 1.1, 1.1)
    updateHitbox('bg5')
    setScrollFactor('bg5', 0.9, 0.9)
    addLuaSprite('bg5', false)

    makeLuaSprite('bg', 'miku/expo/mainstage', -285, -100)
    scaleObject('bg', 1.1, 1.1)
    updateHitbox('bg')
    addLuaSprite('bg', false)

    makeAnimatedLuaSprite('fiestaSalsa2', 'miku/expo/crowdbump', -295, 645)
    addAnimationByPrefix('fiestaSalsa2', 'dance', 'crowdbump', 24, false)
    addAnimationByPrefix('fiestaSalsa2', 'cheer', 'crowdcheer', 24, false)
    addAnimationByPrefix('fiestaSalsa2', 'miss', 'crowdmiss', 24, false)
    setScrollFactor('fiestaSalsa2', 0.9, 0.9)
    scaleObject('fiestaSalsa2', 1.5, 1.5)
    updateHitbox('fiestaSalsa2')

    makeLuaSprite('light1', 'miku/expo/chance/focus_light', -450, -100)
    scaleObject('light1', 1.7, 1.7)
    updateHitbox('light1')
    setScrollFactor('light1', 0.95, 0.95)

    makeAnimatedLuaSprite('fiestaSalsa', 'miku/expo/spotlightdance', -1000, -100)
    addAnimationByIndices('fiestaSalsa', 'light1', 'spotlightdance1', '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11, 12, 13', 24)
    addAnimationByIndices('fiestaSalsa', 'light2', 'spotlightdance1', '14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26', 24)
    setScrollFactor('fiestaSalsa', 0.9, 0.9)
    scaleObject('fiestaSalsa', 1.3, 1.3)
    updateHitbox('fiestaSalsa')

    makeLuaSprite('bgblack', 'miku/expo/chance/blacksocool', -100, -100)
    setScrollFactor('bgblack', 0.8, 0.8)
    scaleObject('bgblack', 2, 2)
    updateHitbox('bgblack')
    setProperty('bgblack.alpha', 0)

    makeAnimatedLuaSprite('perfect', 'miku/expo/chance/Perfect', 100, 150)
    addAnimationByPrefix('perfect', 'perfect', 'Perfect', 24, false)
    addLuaSprite('perfect', true)
    setObjectCamera('perfect', 'other')
    setProperty('perfect.visible', false)

    makeAnimatedLuaSprite('start', 'miku/expo/Songs/songstart', 300, 0)
    addAnimationByPrefix('start', 'Endurance', 'Endurance', 1, true)
    addLuaSprite('start', true)
    setObjectCamera('start', 'hud')
    setProperty('start.visible', false)
end