function onCreate()
    makeAnimatedLuaSprite('bg', 'shaggy/god_bg', -850, -850)
    addAnimationByPrefix('bg', 'sky', 'bg', 24, true)
    addLuaSprite('bg', false)
    setLuaSpriteScrollFactor('bg', 0.1, 0.1)
    scaleLuaSprite('bg', 0.8, 1)
    updateHitbox('bg')
    objectPlayAnimation('bg', 'sky', true)

    makeAnimatedLuaSprite('c', 'shaggy/god_bg', -850, -1250)
    addAnimationByPrefix('c', 'clod', 'cloud_smol', 24, true)
    addLuaSprite('c', false)
    setLuaSpriteScrollFactor('c', 0.3, 0.3)
    objectPlayAnimation('c', 'clod', true)

    makeAnimatedLuaSprite('cloud', 'shaggy/god_bg', -1150, -2900)
    addAnimationByPrefix('cloud', 'cloud', 'cloud_big', 24, true)
    addLuaSprite('cloud', false)
    setLuaSpriteScrollFactor('cloud', 0.3, 0.3)
    objectPlayAnimation('cloud', 'cloud', true)

    makeLuaSprite('mansion', 'shaggy/bg_lemon', -850, -850)
    addLuaSprite('mansion', false)
    setLuaSpriteScrollFactor('mansion', 0.95, 0.95)
    scaleLuaSprite('mansion', 1.5, 1)
    updateHitbox('mansion')

    makeAnimatedLuaSprite('techo', 'shaggy/god_bg', 0, -20)
    addAnimationByPrefix('techo', 'techo', 'broken_techo', 24, true)
    addLuaSprite('techo', false)
    setLuaSpriteScrollFactor('techo', 0.95, 0.95)
    scaleLuaSprite('techo', 1.5, 1)
    updateHitbox('techo')
    objectPlayAnimation('techo', 'techo', true)

    makeAnimatedLuaSprite('gf_rock', 'shaggy/god_bg', 20, 20)
    addAnimationByPrefix('gf_rock', 'gf_rock', 'gf_rock', 24, true)
    addLuaSprite('gf_rock', false)
    setLuaSpriteScrollFactor('gf_rock', 0.8, 0.8)
    objectPlayAnimation('gf_rock', 'gf_rock', true)

    makeAnimatedLuaSprite('rock', 'shaggy/god_bg', 20, 20)
    addAnimationByPrefix('rock', 'rock', 'rock', 24, true)
    addLuaSprite('rock', false)
    setLuaSpriteScrollFactor('rock', 1, 1)
    objectPlayAnimation('rock', 'rock', true)
end