function onCreate()
    makeLuaSprite('bgglitch', 'exe/Phase3/Glitch', -621.1, -395.65)
    addLuaSprite('bgglitch', false)
    setLuaSpriteScrollFactor('bgglitch', 0.9, 1)
    scaleLuaSprite('bgglitch', 1.2, 1.2)
    updateHitbox('bgglitch')

    makeAnimatedLuaSprite('exeglitch', 'exe/NewTitleMenuBG', 0, 0)
    addAnimationByPrefix('exeglitch', 'glitch', 'TitleMenuSSBG instance 1', 24, true)
    addLuaSprite('exeglitch', false)
    scaleLuaSprite('exeglitch', 4.5, 4.5)
    updateHitbox('exeglitch')
    objectPlayAnimation('exeglitch', true)
    setProperty('exeglitch.visible', false)

    makeLuaSprite('trees', 'exe/Phase3/Trees', -607.35, -401.55)
    addLuaSprite('trees', false)
    setLuaSpriteScrollFactor('trees', 0.95, 1)
    scaleLuaSprite('trees', 1.2, 1.2)
    updateHitbox('trees')

    makeLuaSprite('trees2', 'exe/Phase3/Trees2', -623.5, -410.4)
    addLuaSprite('trees2', false)
    setLuaSpriteScrollFactor('trees2', 1, 1)
    scaleLuaSprite('trees2', 1.2, 1.2)
    updateHitbox('trees2')

    makeLuaSprite('grass', 'exe/Phase3/Trees2', -630.4, -266)
    addLuaSprite('grass', false)
    setLuaSpriteScrollFactor('grass', 1.1, 1)
    scaleLuaSprite('grass', 1.2, 1.2)
    updateHitbox('grass')
end